# Generated by Django 2.1.2 on 2019-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_excelfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfiles',
            name='category',
            field=models.CharField(default='mice', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelfiles',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
